### PR TITLE
Fix GetFulfilmentDeliveryDocumentResult filename case issue

### PR DESCRIPTION
**Pull request by ncharlot**
Fix fatal on case sensitive file systems:
```
Fatal error: require_once(): Failed opening required 'vendor/cdiscount/sdkphpapi/sdk/src/core/Fulfilment/GetFulfilmentDeliveryDocumentResult.php' (include_path='.:') in vendor/cdiscount/sdkphpapi/sdk/autoload.php on line 270
```

### CODE REVIEW

**Comment by enrobroy** [comment]
+1 very easy bug to fix, please merge quickly it's fatal error

**Comment by smokarz** [comment]
thats very important fix.. please merge asap

**Comment by gralec99** [comment]
+1, sorry for my english ( ͡° ͜ʖ ͡°)

**Comment by bnowak** [comment]
+1 this basic bug makes this SDK unusable

**Comment by gcmikolaj** [comment]
+1

**Comment by ncharlot** [comment]
If you can't wait for the merge, clone my fork:
https://github.com/ncharlot/API-MarketPlace-SDK-PHP/

**Comment by guillaumecochard** [comment]
It's merged

**Pull request merged**
