### PR TITLE
Cleaning up and little refactoring

### PR DESCRIPTION
**Pull request by bnowak**
Some of changes makes code of this SDK shorter and more clearly. Please give me a feedback if you don't agree with some part of PR. I didn't change any of logic part.

Especially uncommented echos was inconvenient during calling a requests.

### CODE REVIEW

**Comment by smokarz** [comment]
+1 good clean up, those rubbish shouldnt exist in master branch guys

**Comment by enrobroy** [comment]
+1 good refactoring getting ride off unnecessary makes developing new features faster

**Comment by gcmikolaj** [comment]
+1

**Comment by gralec99** [comment]
+1

**Pull request merged**
